### ISSUE TITLE
Port 8443 not exposed

### ISSUE THREAD

**Issue by giraone** [disaster37/rancher-alfresco#1]
When I start the container it states

```
INFO: Loaded APR based Apache Tomcat Native library 1.1.32 using APR version 1.4.6.
INFO: Initializing ProtocolHandler ["http-bio-8443"]
```

so I assume Tomcat is configured also to server HTTPS on port 8443. Why is this port not exposed in the Dockerfile?

**Comment by disaster37** [comment]
Hi. I expose only 8080 because if you need HTTPS, you must prefere to add https reverse proxy on front like Nginx (image Docker jwilder/nginx-proxy).

If you realy need 8443 now, you can use option -p 8443:8443 ;)
