### ISSUE TITLE
upload file fail

### ISSUE THREAD

**Issue by kingzus** [disaster37/rancher-alfresco#3]
when lanch a alfesco contain,upload file failed. The fault seems like running alfresco by root. but change the run user by alfresco .the isssue still exsits.
EVERE: Servlet.service() for servlet [default] in context with path [/share] threw exception [Possible CSRF attack noted when comparing token in session and request parameter. Request: POST /share/proxy/alfresco/api/upload] with root cause
avax.servlet.ServletException: Possible CSRF attack noted when comparing token in session and request parameter. Request: POST /share/proxy/alfresco/api/upload

**Comment by disaster37** [comment]
hi. It's maybee you use DNS to access on share like http://ged.my-domain.com.
If right, have you try to add environment variable `REVERSE_PROXY_URL=http://ged.my-domain.com` ?

**Comment by kingzus** [comment]
thanks for yor reply. I got it. the issue maybe  causes by  browser caching. I open the alfesco using IP and port in browser,then I opened it with domain. After that,the issue came. At last  i use another  browser,the issue was gone.And I purged  the browser  cache,it didn't  happen again!

**Comment by disaster37** [comment]
Ok, I'm happy to listen that your matter is done ;)
