### ISSUE TITLE
Change image name in docker deployment instructions

### ISSUE THREAD

**Issue by jpstaub** [disaster37/rancher-alfresco#5]
First, thanks for putting together a Docker repo for Alfresco. One problem was noted during deployment which is detailed below.

Current repo name = webcenter/rancher-alfresco:5.1-201605-1

Actual repo name = webcenter/rancher-alfresco:v5.1-201605-1

Regards,
Jake

**Comment by disaster37** [comment]
It's fixed on last docker images.
