### ISSUE TITLE
Problem in ldap configuration script 

### ISSUE THREAD

**Issue by thordickinson** [disaster37/rancher-alfresco#6]
Hi, I think you mispelled the ldap configuration file path in the init.py script. 

This is causing me this error:

`Traceback (most recent call last):
  File "/app/init.py", line 510, in <module>
    serviceRun.set_ldap(os.getenv('LDAP_ENABLED', 'false'), os.getenv('LDAP_AUTH_FORMAT'), os.getenv('LDAP_HOST'), os.getenv('LDAP_USER'), os.getenv('LDAP_PASSWORD'), os.getenv('LDAP_ADMINS'), os.getenv('LDAP_GROUP_SEARCHBASE'), os.getenv('LDAP_USER_SEARCHBASE'))
  File "/app/init.py", line 208, in set_ldap
    self.replace_all(ALFRESCO_PATH + '/tomcat/shared/classes/alfresco/extension/subsystems/Authentication/ldap/ldap1/ldap-authentication.propertie', 'ldap.authentication.userNameFormat\s*=.*', 'ldap.authentication.userNameFormat=' + auth_format)
  File "/app/init.py", line 429, in replace_all
    f = open(file,'r')
`

may be the file name is authentication.properties instead authentication.propertie?

**Comment by disaster37** [comment]
hi,

thanks for your help, I fix this on last docker image (201612GA)
